kind: NamespaceSelector
apiVersion: nomos.dev/v1alpha1
metadata:
  name: selectorEnvNonProd.acme.com
spec:
  selector:
    matchExpressions:                                                                                                                         
      - {key: environment, operator: NotIn, values: [production]}


